# Computação Numérica com Numpy

Pacote para computação numérica em Python

Para instalar

pip install -U numpy


In [ ]:
!pip install -U numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 38.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.26.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.1 which is incompatible.


Numpy é um pacote com ferramentas para aplicações numéricas e científicas, incluindo rotinas matriciais, de álgebra linear, trabsformada de Fourrier, geração de numéros aleatórios, etc...

No numpy, temos dois tipos principais de objetos:

* ndarray: arrays de dimensão qualquer
* matrix: matrizes de duas dimensões (linhas e colunas)

Todos os elementos das matrizes e arrays devem ser do mesmo tipo!

Vamos definir a matriz $A$:

$A = \left[ \begin{array}[cc] \\
1 & 2 \\
3 & 4
\end{array} \right]$

In [ ]:
import numpy as np
A = np.matrix(  [ [1,2], [3,4] ]    )
A

matrix([[1, 2],
        [3, 4]])

In [ ]:
print(A)

[[1 2]
 [3 4]]


In [ ]:
#acessano um elemnto da matriz
A[0, 1]   #acessa o elemento na linha 0, coluna 1 da matriz

2

In [ ]:
#acessando uma linha inteira
A[1]   #acessa a linha 1 da matriz

matrix([[3, 4]])

In [ ]:
A[ :, 0]  #Acessa a cluna 0 da matriz

matrix([[1],
        [3]])

In [ ]:
# a função zeros gera um array de zeros
M = np.matrix(   np.zeros( (4,5) )    )   #gera uma matriz de 4 linhas e colunas só de zeros
M

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# afunção ones gera um array de um's
N = np.matrix(  np.ones( (5,8) )   )
N

matrix([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#a função randint gera um array de números inteiros aleatórios em um intervalo
import numpy.random as npr
#gerando uma matriz inteira aleatória de 2 linhas e colunas no intervalo [-10  10]
R = np.matrix(  npr.randint( -10, 10, (2, 3)  )  )
R

matrix([[ 1, -8, -7],
        [ 0, -7, -1]])

In [ ]:
# a função eye gera array identidade
B = np.matrix(  np.eye(2, 2),  int  )
B

matrix([[1, 0],
        [0, 1]])

In [ ]:
M

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
R

matrix([[ 1, -8, -7],
        [ 0, -7, -1]])

In [ ]:
M[ 1:3, 1:4]  # retorna o subbloco da matriz (submatriz) que vai da linha 1 até a 3 e da coluna 1 até a 4

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
M[1:3, 1:4] = R
M

matrix([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -8., -7.,  0.],
        [ 0.,  0., -7., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
B

matrix([[1, 0],
        [0, 1]])

In [ ]:
#multiplicando a matriz por um escalar
B = 4*B
B

matrix([[4, 0],
        [0, 4]])

In [ ]:
np.ones( (4,3) )/5

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [ ]:
A

matrix([[1, 2],
        [3, 4]])

In [ ]:
B

matrix([[4, 0],
        [0, 4]])

In [ ]:
#podemos somar matrizes
C = A + B
C

matrix([[5, 2],
        [3, 8]])

In [ ]:
#ou multiplicá-las
D = A*B
D

matrix([[ 4,  8],
        [12, 16]])

In [ ]:
#ou fazer potências
A**2   # A * A

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
#inversa da matriz
Ainv = A**-1
Ainv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
Ainv * A

matrix([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]])

In [ ]:
#um pouco sobre erros numéricos

#qualquer operação envolvendo float em qualquer linguagem está sujeita a erros, incluindo somas

x = 0.1 + 0.2
x

0.30000000000000004

In [ ]:
A**0

matrix([[1, 0],
        [0, 1]])

In [ ]:
M * R

ValueError: ignored

In [ ]:
# a multiplicação entre arrays é feito elemtno a elemtno
A*B

matrix([[ 4,  8],
        [12, 16]])

In [ ]:
np.array(A) * np.array(B)

array([[ 4,  0],
       [ 0, 16]])

In [ ]:
np.array(A)**2  #eleva ao quadrado elemento a elemento

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
np.transpose(A) #gera matriz transposta

matrix([[1, 3],
        [2, 4]])

In [ ]:
A.T    #outra forma de gerar a transposta

matrix([[1, 3],
        [2, 4]])

In [ ]:
R.shape   # o atributo shape retorna uma tupla com as dimensões da matriz

(2, 3)

In [ ]:
R

matrix([[ 1, -8, -7],
        [ 0, -7, -1]])

In [ ]:
R.shape = (6, 1)
R

matrix([[ 1],
        [-8],
        [-7],
        [ 0],
        [-7],
        [-1]])

In [ ]:
R.shape = (3, 2)
R

matrix([[ 1, -8],
        [-7,  0],
        [-7, -1]])

# concatenação de matrizes

* por linha (vertical): vstack
* por coluna (horizontal): hstack

In [ ]:
np.vstack( (A,B) )

matrix([[1, 2],
        [3, 4],
        [4, 0],
        [0, 4]])

In [ ]:
np.hstack( (A,B) )

matrix([[1, 2, 4, 0],
        [3, 4, 0, 4]])

Existem funções que podem ser aplicadas a todos os elementos de uma matriz: sqrt, exp, log, sin, cos

In [ ]:
np.sqrt(A)

matrix([[1.        , 1.41421356],
        [1.73205081, 2.        ]])

In [ ]:
np.sum( A )

10

In [ ]:
np.max(A)

4

Poemos fazer coisas bem irabolantes com o submódulod e álgebra linear

In [ ]:
import numpy.linalg as la

autovals, autovets = la.eig(A)
print("autovals: ", autovals)
print("autovets: ", autovets)

autovals:  [-0.37228132  5.37228132]
autovets:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#cálculo de determinante
la.det(A)


-2.0000000000000004

In [ ]:
#posto da matriz
la.matrix_rank(A)

2

In [ ]:
#la.norm
la.norm(A)

5.477225575051661

Vamos resolver

Ax = b

1x + 2y = 10

3x + 4y = 20


In [ ]:
b = [10, 20]

In [ ]:
x = la.solve(A, b)
x

array([0., 5.])